import fs from "fs/promises";
import path from "path";
import type { ArtifactSpec } from "../artifacts.js";
import type { ArtifactCheck } from "../validator.js";

export const ARTIFACT_BRIEFS_DIR = "artifact-briefs";

export interface ArtifactBriefContext {
  workdir: string;
  evidenceBrief: string;
  dependencyMarkdown: string;
  pipelineStatus: string;
}

export interface RunMetric {
  phase: string;
  artifact?: string;
  durationMs: number;
  status: string;
  detail?: string;
}

export function artifactBriefFilename(spec: ArtifactSpec): string {
  return `${spec.filename.replace(/\.md$/, "")}.brief.md`;
}

export async function buildArtifactBrief(
  spec: ArtifactSpec,
  ctx: ArtifactBriefContext,
): Promise<string> {
  const evidenceReport = await readIfExists(path.join(ctx.workdir, "evidence-report.md"));
  const evidenceLedger = await readIfExists(path.join(ctx.workdir, "evidence-ledger.md"));

  return `# Artifact Brief: ${spec.filename}

> Status: Deterministic planning brief generated by Pantheon.
> Purpose: ${spec.purpose}

## Required Sections

${spec.requiredSections.map((section) => `- ${section}`).join("\n")}

## Validator Requirements

- Generate exactly \`${spec.filename}\`.
- Use Markdown headings.
- Preserve \`[source: <relative-path>]\` citations.
- Label unsupported claims as Inference, Assumption, Evidence gap, or Data needed.
- Standard artifacts need 35+ non-empty lines and 4+ headings unless learned style validation overrides the structure.
- \`decision-packet.md\` must stay under 500 words.

## Source-Backed Evidence To Use

${ctx.evidenceBrief}

## Evidence Coverage

${evidenceReport || "- Evidence report is missing; treat coverage as an Evidence gap."}

## Evidence Ledger Snapshot

${truncate(evidenceLedger || "- Evidence ledger is missing.", 12_000)}

## Dependency Artifact Summary

${ctx.dependencyMarkdown || "No prior artifact dependencies."}

## Pipeline Status

${ctx.pipelineStatus || "- No prior pipeline status."}

## Assumptions And Evidence Gaps To Preserve

- Assumption: this brief is a structured planning input, not final prose.
- Evidence gap: any claim not present in the evidence brief, evidence ledger, or dependency artifacts must stay labeled.
- Evidence gap: if a required section lacks direct evidence, write the section with explicit Data needed bullets rather than inventing certainty.
`;
}

export async function writeArtifactBrief(
  runDir: string,
  spec: ArtifactSpec,
  brief: string,
): Promise<string> {
  const dir = path.join(runDir, ARTIFACT_BRIEFS_DIR);
  await fs.mkdir(dir, { recursive: true });
  const filepath = path.join(dir, artifactBriefFilename(spec));
  await fs.writeFile(filepath, brief, "utf8");
  return filepath;
}

export async function readArtifactBrief(runDir: string, spec: ArtifactSpec): Promise<string> {
  return readIfExists(path.join(runDir, ARTIFACT_BRIEFS_DIR, artifactBriefFilename(spec)));
}

export function renderArtifactBriefForPrompt(brief: string, maxChars: number): string {
  return truncate(brief, maxChars);
}

export function buildDeterministicFallbackArtifact(
  spec: ArtifactSpec,
  brief: string,
  validationFailure?: ArtifactCheck,
): string {
  if (spec.filename === "decision-packet.md") {
    return buildDecisionPacketFallback(spec, brief, validationFailure);
  }

  const citation = firstCitation(brief);
  const failureText = validationFailure?.failures.length
    ? validationFailure.failures.join("; ")
    : "model generation unavailable or skipped";
  const sections = spec.requiredSections.length > 0 ? spec.requiredSections : ["Summary", "Evidence", "Risks", "Next Steps"];

  return `# ${titleFor(spec.filename)}

> Status: Deterministic fallback generated by Pantheon.
> TL;DR: This artifact was assembled from the deterministic artifact brief because model generation was unavailable, skipped, or failed validation.

## Fallback Context

- Purpose: ${spec.purpose}
- Fallback reason: ${failureText}
- Primary citation to preserve: ${citation}
- Assumption: this artifact is structurally complete but should be polished by a PM before executive use.
- Evidence gap: claims remain limited to the artifact brief and prior source-grounded artifacts.

${sections.map((section) => fallbackSection(section, spec, citation)).join("\n\n")}

## Validation Notes

- This fallback intentionally includes the required sections for \`${spec.filename}\`.
- It preserves source citation format for citation audit compatibility: ${citation}
- It labels unsupported synthesis as Assumption, Inference, Evidence gap, or Data needed.
- If model polish is available later, rerun with \`PANTHEON_ARTIFACT_MODEL_MODE=polish\`.
`;
}

function buildDecisionPacketFallback(
  spec: ArtifactSpec,
  brief: string,
  validationFailure?: ArtifactCheck,
): string {
  const citation = firstCitation(brief);
  const failureText = validationFailure?.failures.length
    ? validationFailure.failures.join("; ")
    : "model generation unavailable or skipped";
  return `# Decision Packet

> Status: Deterministic fallback generated by Pantheon.
> TL;DR: Proceed only with evidence-backed next steps; this packet needs PM polish before leadership use.

## Recommendation

Use the evidence-led packet as a planning baseline, not a final commitment. ${citation}

## Why now

The workspace contains enough signal to continue product discovery, but unsupported claims should remain labeled as Assumption or Evidence gap.

## Why this wedge

Prioritize the wedge with the clearest customer signal, metric impact, and delivery feasibility in the dependency artifacts.

## Top risks

Risk: fallback generated because ${failureText}. Risk: evidence may be incomplete. Risk: model polish was skipped or failed.

## Asks

Ask: review source evidence. Ask: confirm the chosen wedge. Ask: validate privacy, technical, and launch constraints.

## Next decision

Decide whether to rerun with model polish, collect missing evidence, or move this fallback packet into human review.
`;
}

function fallbackSection(section: string, spec: ArtifactSpec, citation: string): string {
  const lower = section.toLowerCase();
  const extras: string[] = [];
  if (spec.filename === "evals.md" || lower.includes("ship")) {
    extras.push(`- Ship gate: require citation audit warnings to be reviewed before use. ${citation}`);
    extras.push(`- Adversarial test: verify unsupported claims remain labeled as Evidence gap or Assumption. ${citation}`);
  }
  if (lower.includes("risk") || spec.filename === "risk-review.md") {
    extras.push(`- Risk: downstream recommendations may be under-polished because this is a deterministic fallback. ${citation}`);
  }
  return `## ${section}

- Confirmed: use source-backed evidence from the artifact brief and dependency artifacts. ${citation}
- Inference: this section should be interpreted as a planning scaffold until a PM reviews it.
- Assumption: the available evidence is sufficient to draft this section, but not sufficient to remove all uncertainty.
- Evidence gap: add direct customer, metric, technical, or legal evidence before treating this section as final.
- Data needed: review \`artifact-briefs/${artifactBriefFilename(spec)}\` for the exact evidence and dependency context.
${extras.join("\n")}`;
}

export async function writeRunMetrics(runDir: string, metrics: RunMetric[]): Promise<void> {
  await fs.writeFile(path.join(runDir, "run-metrics.json"), `${JSON.stringify(metrics, null, 2)}\n`, "utf8");
  const lines = [
    "# Run Metrics",
    "",
    "> Status: Generated by Pantheon.",
    "",
    "| Phase | Artifact | Duration ms | Status | Detail |",
    "| --- | --- | ---: | --- | --- |",
    ...metrics.map((metric) =>
      `| ${metric.phase} | ${metric.artifact ?? "-"} | ${Math.round(metric.durationMs)} | ${metric.status} | ${(metric.detail ?? "-").replace(/\|/g, "\\|")} |`,
    ),
    "",
  ];
  await fs.writeFile(path.join(runDir, "run-metrics.md"), lines.join("\n"), "utf8");
}

function titleFor(filename: string): string {
  return filename
    .replace(/\.md$/, "")
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function firstCitation(text: string): string {
  for (const match of text.matchAll(/\[source:\s*([^\]]+?)\s*\]/gi)) {
    const citation = match[1].trim();
    if (citation && citation !== "<relative-path>") {
      return `[source: ${citation}]`;
    }
  }
  return "[source: context-summary.md]";
}

function truncate(content: string, maxChars: number): string {
  if (content.length <= maxChars) return content;
  return `${content.slice(0, Math.max(0, maxChars - 54)).replace(/\s+$/, "")}\n\n[Truncated by Pantheon artifact brief budget.]`;
}

async function readIfExists(filepath: string): Promise<string> {
  try {
    return await fs.readFile(filepath, "utf8");
  } catch {
    return "";
  }
}
