import fs from "fs/promises";
import path from "path";

export const PANTHEON_OUTPUT_DIR = "pantheon-output";

const SUPPORTED_EXTENSIONS = new Set([
  ".md",
  ".markdown",
  ".txt",
  ".csv",
  ".tsv",
  ".json",
  ".sql",
  ".log",
  ".yaml",
  ".yml",
  ".html",
  ".xml",
]);
const EXCLUDED_DIRS = new Set([
  PANTHEON_OUTPUT_DIR,
  ".git",
  ".hg",
  ".svn",
  "node_modules",
  "dist",
  "build",
  "coverage",
  ".next",
  ".nuxt",
  ".cache",
  ".turbo",
  ".vercel",
  "target",
  "vendor",
]);
const EXCLUDED_FILES = new Set([".DS_Store"]);
const MAX_FILE_BYTES = Number(process.env.PANTHEON_MAX_CONTEXT_FILE_BYTES ?? 250_000);
const MAX_TOTAL_CHARS = Number(process.env.PANTHEON_MAX_CONTEXT_CHARS ?? 220_000);

export interface ContextFile {
  relativePath: string;
  bytes: number;
  content: string;
}

export interface SkippedFile {
  relativePath: string;
  reason: string;
}

export interface FileDiscoveryOptions {
  supportedExtensions?: Set<string>;
  unsupportedReason?: string;
  maxFileBytes?: number;
  maxTotalChars?: number;
}

export interface FileDiscoveryResult {
  supportedFiles: ContextFile[];
  skippedFiles: SkippedFile[];
  unsupportedFiles: SkippedFile[];
  totalBytes: number;
  totalChars: number;
}

export interface WorkspaceContext {
  workspaceDir: string;
  supportedFiles: ContextFile[];
  skippedFiles: SkippedFile[];
  unsupportedFiles: SkippedFile[];
  totalBytes: number;
  totalChars: number;
}

export interface WorkspaceOutputPaths {
  outputRoot: string;
  runDir: string;
  latestDir: string;
}

export async function buildWorkspaceContext(workspaceDir: string): Promise<WorkspaceContext> {
  const discovery = await discoverWorkspaceFiles(workspaceDir, {
    supportedExtensions: SUPPORTED_EXTENSIONS,
    unsupportedReason: "unsupported file type in V1 text-first ingestion",
    maxFileBytes: MAX_FILE_BYTES,
    maxTotalChars: MAX_TOTAL_CHARS,
  });
  return { workspaceDir, ...discovery };
}

export async function discoverWorkspaceFiles(
  workspaceDir: string,
  options: FileDiscoveryOptions = {},
): Promise<FileDiscoveryResult> {
  const supportedExtensions = options.supportedExtensions ?? SUPPORTED_EXTENSIONS;
  const unsupportedReason = options.unsupportedReason ?? "unsupported file type";
  const maxFileBytes = options.maxFileBytes ?? MAX_FILE_BYTES;
  const maxTotalChars = options.maxTotalChars ?? MAX_TOTAL_CHARS;
  const supportedFiles: ContextFile[] = [];
  const skippedFiles: SkippedFile[] = [];
  const unsupportedFiles: SkippedFile[] = [];
  let totalBytes = 0;
  let totalChars = 0;

  async function walk(dir: string): Promise<void> {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    entries.sort((a, b) => a.name.localeCompare(b.name));

    for (const entry of entries) {
      if (entry.name.startsWith(".") || EXCLUDED_FILES.has(entry.name)) continue;

      const fullPath = path.join(dir, entry.name);
      const relativePath = normalizeRelativePath(path.relative(workspaceDir, fullPath));
      if (entry.isDirectory()) {
        if (shouldExcludeDirectory(entry.name)) continue;
        await walk(fullPath);
        continue;
      }
      if (!entry.isFile()) continue;
      if (EXCLUDED_FILES.has(entry.name)) continue;

      const ext = path.extname(entry.name).toLowerCase();
      if (!supportedExtensions.has(ext)) {
        unsupportedFiles.push({ relativePath, reason: unsupportedReason });
        continue;
      }

      const stat = await fs.stat(fullPath);
      if (stat.size > maxFileBytes) {
        skippedFiles.push({
          relativePath,
          reason: `file exceeds ${maxFileBytes} byte ingestion limit`,
        });
        continue;
      }

      if (totalChars >= maxTotalChars) {
        skippedFiles.push({
          relativePath,
          reason: `workspace context reached ${maxTotalChars} character ingestion limit`,
        });
        continue;
      }

      const raw = await fs.readFile(fullPath, "utf8");
      const remainingChars = maxTotalChars - totalChars;
      const content =
        raw.length > remainingChars
          ? `${raw.slice(0, remainingChars)}\n\n[Truncated by Pantheon context budget.]`
          : raw;
      supportedFiles.push({ relativePath, bytes: stat.size, content });
      totalBytes += stat.size;
      totalChars += content.length;
    }
  }

  await walk(workspaceDir);
  return { supportedFiles, skippedFiles, unsupportedFiles, totalBytes, totalChars };
}

export function makeWorkspaceOutputPaths(workspaceDir: string, stamp: string): WorkspaceOutputPaths {
  const outputRoot = path.join(workspaceDir, PANTHEON_OUTPUT_DIR);
  return {
    outputRoot,
    runDir: path.join(outputRoot, "runs", stamp),
    latestDir: path.join(outputRoot, "latest"),
  };
}

export function renderDeterministicContextSummary(ctx: WorkspaceContext): string {
  return `# Context Summary

> Status: Generated by Pantheon before provider execution.
> TL;DR: Pantheon treated the current folder as the workspace, ingested supported text-first files, and left raw context untouched.

## Workspace

- Folder: \`${ctx.workspaceDir}\`
- Supported files ingested: ${ctx.supportedFiles.length}
- Unsupported files listed as context gaps: ${ctx.unsupportedFiles.length}
- Skipped supported files: ${ctx.skippedFiles.length}
- Ingested bytes: ${ctx.totalBytes}
- Ingested characters: ${ctx.totalChars}

## Supported Files Ingested

${ctx.supportedFiles.length === 0 ? "- None" : ctx.supportedFiles.map((file) => `- \`${file.relativePath}\` (${file.bytes} bytes)`).join("\n")}

## Unsupported Context Gaps

${ctx.unsupportedFiles.length === 0 ? "- None" : ctx.unsupportedFiles.map((file) => `- \`${file.relativePath}\`: ${file.reason}`).join("\n")}

## Skipped Files

${ctx.skippedFiles.length === 0 ? "- None" : ctx.skippedFiles.map((file) => `- \`${file.relativePath}\`: ${file.reason}`).join("\n")}
`;
}

export function buildWorkspaceRunBrief(ctx: WorkspaceContext): string {
  const inventory = renderContextInventory(ctx);
  const contents = renderContextContents(ctx);

  return `Run Pantheon in folder-native mode.

Current run date: ${new Date().toISOString().slice(0, 10)}.

The folder is the prompt. Do not ask clarifying questions mid-run. Infer the product/problem context from the files below, generate the standard Pantheon product packet, validate your own work, and write outputs as Markdown artifacts.

Pantheon has already written a deterministic \`context-summary.md\` from the local scanner. Do not emit or overwrite \`context-summary.md\`; use it as context. You must produce the standard 13 Pantheon packet artifacts:
1. evidence-ledger.md
2. product-vision.md
3. user-personas-jtbd.md
4. competitive-deconstruction.md
5. opportunity-scorecard.md
6. prd-v1.md
7. system-design.md
8. evals.md
9. roadmap.md
10. launch-plan.md
11. risk-review.md
12. decision-packet.md
13. quality-report.md

Rules:
- Treat the ingested folder files as the primary evidence source.
- Label inferred user stories, assumptions, strategy, personas, and market claims unless directly grounded in a file.
- If context is missing, write Evidence gap or Data needed rather than fabricating certainty.
- Do not mention stale model names as current. Use current runtime/user-provided models or capability tiers.
- V1 ingests text-first files only. Unsupported files below are context gaps; do not pretend you read them.
- Keep raw workspace context untouched. Outputs are written by Pantheon into \`pantheon-output\`.
- Do not claim the packet passed deterministic validation unless the validator report says so. Your \`quality-report.md\` is a self-review, not the source of truth for pass/fail.

${inventory}

${contents}`;
}

/**
 * Filenames that are generated as scratch/debug dumps during a run and must
 * not be mirrored into the clean `latest/` folder. Covers `raw-output.md`,
 * `raw-output-<artifact>.md`, and `raw-output-<provider>-error.md`.
 */
function isMirrorableArtifact(filename: string): boolean {
  if (!filename.endsWith(".md")) return false;
  if (filename === "raw-output.md" || filename.startsWith("raw-output-")) return false;
  if (filename === "evidence-cards-summary.md") return false;
  return true;
}

export async function mirrorRunToLatest(runDir: string, latestDir: string): Promise<void> {
  await fs.rm(latestDir, { recursive: true, force: true });
  await fs.mkdir(latestDir, { recursive: true });
  const entries = await fs.readdir(runDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile() || !isMirrorableArtifact(entry.name)) continue;
    await fs.copyFile(path.join(runDir, entry.name), path.join(latestDir, entry.name));
  }
}

function renderContextInventory(ctx: WorkspaceContext): string {
  return `# Workspace Context Inventory

Workspace folder: \`${ctx.workspaceDir}\`

## Supported Files

${ctx.supportedFiles.length === 0 ? "- None" : ctx.supportedFiles.map((file) => `- \`${file.relativePath}\` (${file.bytes} bytes)`).join("\n")}

## Unsupported Files

${ctx.unsupportedFiles.length === 0 ? "- None" : ctx.unsupportedFiles.map((file) => `- \`${file.relativePath}\`: ${file.reason}`).join("\n")}

## Skipped Files

${ctx.skippedFiles.length === 0 ? "- None" : ctx.skippedFiles.map((file) => `- \`${file.relativePath}\`: ${file.reason}`).join("\n")}`;
}

function renderContextContents(ctx: WorkspaceContext): string {
  if (ctx.supportedFiles.length === 0) {
    return `# Ingested File Contents

No supported text-first files were found. Generate the packet only if the folder name and available inventory give enough signal; otherwise mark the packet Not demo-ready and list data needed.`;
  }

  const files = ctx.supportedFiles.map((file) => {
    return `## File: ${file.relativePath}

\`\`\`text
${file.content}
\`\`\``;
  });
  return `# Ingested File Contents

${files.join("\n\n")}`;
}

function shouldExcludeDirectory(name: string): boolean {
  return EXCLUDED_DIRS.has(name) || name.startsWith(".");
}

function normalizeRelativePath(relativePath: string): string {
  return relativePath.split(path.sep).join("/");
}
